### PR TITLE
Autopopulate namespace from API calls

### PR DESCRIPTION
**Pull request by TheAlphaNerd**
Currently you have to know the name of the namespace you would like
to use and manually enter it. This commit uses the whisk api to get
the available namespaces and populates a drop down menu to select from.

### CODE REVIEW

**Comment by knolleary** [comment]
Thanks @TheAlphaNerd - with the move of repo out of the node-red org we haven't figured out the CLA position for this repo as we've been focused on the move of everything else to JSF. Will figure out what we need before we can merge this.

**Comment by animeshsingh** [comment]
Hi @knolleary - any update on the CLA position?

**Comment by knolleary** [comment]
Hi - sorry for the delays.

We're going to use a DCO approach for this project. Commits need to be signed to indicate they are made under the terms of the DCO1.1 - have added a CONTRIBUTING file to this affect.

@TheAlphaNerd can you sign your commit and then we can get this merged?

**Comment by TheAlphaNerd** [comment]
@knolleary signed off. I would like to get review from @jthomas before this lands if possible

**Comment by knolleary** [comment]
@TheAlphaNerd so would I. @jthomas can we get a LTGM?

**Comment by jthomas** [comment]
LGTM.

**Pull request merged**
